DO $$
DECLARE
    chessId INT;
    cyclingId INT;
BEGIN
    SELECT id INTO chessId
    FROM t_hobby
    WHERE name = 'Chess';
    
    SELECT id INTO cyclingId
    FROM t_hobby
    WHERE name = 'Cycling';

INSERT INTO t_event(id, title, start_date, end_date, hobby_fk)
VALUES (nextval('event_pk_seq'), 'Tata Steel Masters', cyd(1, 17), cyd(2, 2), @chessId),
       (nextval('event_pk_seq'), 'Shenzhen Masters', cyd(3, 23), cyd(4, 1), @chessId),
       (nextval('event_pk_seq'), 'American Cup', cyd(3, 15), cyd(3, 24), @chessId),
       (nextval('event_pk_seq'), 'Superbet Chess Classic Romania', cyd(5, 7), cyd(5, 16), @chessId),
       (nextval('event_pk_seq'), 'Norway Chess', cyd(5, 26), cyd(6, 6), @chessId),
       (nextval('event_pk_seq'), 'UzChess Cup', cyd(6, 19), cyd(6, 27), @chessId),
       (nextval('event_pk_seq'), 'Chennai Grand Masters', cyd(8, 7), cyd(8, 16), @chessId),
       (nextval('event_pk_seq'), 'Sinquefield Cup', cyd(7, 18), cyd(8, 28), @chessId),
       (nextval('event_pk_seq'), 'Grand Swiss', cyd(9, 3), cyd(9, 15), @chessId),
       (nextval('event_pk_seq'), 'U.S. Chess Championship', cyd(10, 11), cyd(10, 25), @chessId),
       (nextval('event_pk_seq'), 'Chess World Cup', cyd(10, 31), cyd(11, 27), @chessId),
       (nextval('event_pk_seq'), 'Tata Steel Masters', nyd(1, 17), nyd(2, 2), @chessId),
       (nextval('event_pk_seq'), 'Shenzhen Masters', nyd(3, 23), nyd(4, 1), @chessId),
       (nextval('event_pk_seq'), 'American Cup', nyd(3, 15), nyd(3, 24), @chessId),
       (nextval('event_pk_seq'), 'Superbet Chess Classic Romania', nyd(5, 7), nyd(5, 16), @chessId),
       (nextval('event_pk_seq'), 'Norway Chess', nyd(5, 26), nyd(6, 6), @chessId),
       (nextval('event_pk_seq'), 'UzChess Cup', nyd(6, 19), nyd(6, 27), @chessId),
       (nextval('event_pk_seq'), 'Chennai Grand Masters', nyd(8, 7), nyd(8, 16), @chessId),
       (nextval('event_pk_seq'), 'Sinquefield Cup', nyd(7, 18), nyd(8, 28), @chessId),
       (nextval('event_pk_seq'), 'Grand Swiss', nyd(9, 3), nyd(9, 15), @chessId),
       (nextval('event_pk_seq'), 'U.S. Chess Championship', nyd(10, 11), nyd(10, 25), @chessId),
       (nextval('event_pk_seq'), 'Chess World Cup', nyd(10, 31), nyd(11, 27), @chessId)
;

INSERT INTO t_event(id, title, start_date, end_date, hobby_fk)
VALUES (nextval('event_pk_seq'), 'Tour Down Under', cyd(1, 21), cyd(1, 26), @cyclingId),
       (nextval('event_pk_seq'), 'Tour of Valencia', cyd(2, 05), cyd(2, 09), @cyclingId),
       (nextval('event_pk_seq'), 'UAE Tour', cyd(2, 17), cyd(2, 23), @cyclingId),
       (nextval('event_pk_seq'), 'Ruta del Sol', cyd(2, 19), cyd(2, 23), @cyclingId),
       (nextval('event_pk_seq'), 'Volta ao Algarve', cyd(2, 19), cyd(2, 23), @cyclingId),
       (nextval('event_pk_seq'), 'O Gran Camiño', cyd(2, 26), cyd(3, 03), @cyclingId),
       (nextval('event_pk_seq'), 'Omloop Het Nieuwsblad', cyd(3, 01), cyd(3, 01), @cyclingId),
       (nextval('event_pk_seq'), 'Kuurne – Brussels – Kuurne', cyd(3, 02), cyd(3, 02),
        @cyclingId),
       (nextval('event_pk_seq'), 'Strade Bianche Donne', cyd(3, 08), cyd(3, 08), @cyclingId),
       (nextval('event_pk_seq'), 'Strade Bianche', cyd(3, 08), cyd(3, 08), @cyclingId),
       (nextval('event_pk_seq'), 'Paris – Nice', cyd(3, 09), cyd(3, 16), @cyclingId),
       (nextval('event_pk_seq'), 'Tirreno – Adriatico', cyd(3, 10), cyd(3, 16), @cyclingId),
       (nextval('event_pk_seq'), 'Milan – San Remo (women)', cyd(3, 22), cyd(3, 22),
        @cyclingId),
       (nextval('event_pk_seq'), 'Milan – San Remo (men)', cyd(3, 22), cyd(3, 22), @cyclingId),
       (nextval('event_pk_seq'), 'Volta a Catalunya', cyd(3, 24), cyd(3, 30), @cyclingId),
       (nextval('event_pk_seq'), 'E3 Saxo Classic', cyd(3, 28), cyd(3, 28), @cyclingId),
       (nextval('event_pk_seq'), 'Dwars door Vlaanderen', cyd(4, 02), cyd(4, 02), @cyclingId),
       (nextval('event_pk_seq'), 'Tour of Flanders (women)', cyd(4, 06), cyd(4, 06),
        @cyclingId),
       (nextval('event_pk_seq'), 'Tour of Flanders (men)', cyd(4, 06), cyd(4, 06), @cyclingId),
       (nextval('event_pk_seq'), 'Itzulia Basque Country', cyd(4, 07), cyd(4, 12), @cyclingId),
       (nextval('event_pk_seq'), 'Paris – Roubaix Femmes', cyd(4, 12), cyd(4, 12), @cyclingId),
       (nextval('event_pk_seq'), 'Paris – Roubaix', cyd(4, 13), cyd(4, 13), @cyclingId),
       (nextval('event_pk_seq'), 'Brabantse Pijl', cyd(4, 18), cyd(4, 18), @cyclingId),
       (nextval('event_pk_seq'), 'Amstel Gold Race (women)', cyd(4, 20), cyd(4, 20),
        @cyclingId),
       (nextval('event_pk_seq'), 'Amstel Gold Race (men)', cyd(4, 20), cyd(4, 20), @cyclingId),
       (nextval('event_pk_seq'), 'Tour of the Alps', cyd(4, 21), cyd(4, 25), @cyclingId),
       (nextval('event_pk_seq'), 'Flèche Wallonne Femmes', cyd(4, 23), cyd(4, 23), @cyclingId),
       (nextval('event_pk_seq'), 'Flèche Wallonne', cyd(4, 23), cyd(4, 23), @cyclingId),
       (nextval('event_pk_seq'), 'Bastogne – Liège Femmes', cyd(4, 27), cyd(4, 27), @cyclingId),
       (nextval('event_pk_seq'), 'Liège – Bastogne – Liège', cyd(4, 27), cyd(4, 27),
        @cyclingId),
       (nextval('event_pk_seq'), 'Tour de Romandie', cyd(5, 29), cyd(6, 04), @cyclingId),
       (nextval('event_pk_seq'), 'Vuelta Femenina', cyd(5, 04), cyd(5, 10), @cyclingId),
       (nextval('event_pk_seq'), 'Giro d’Italia', cyd(5, 09), cyd(6, 01), @cyclingId),
       (nextval('event_pk_seq'), 'Critérium du Dauphiné', cyd(6, 08), cyd(6, 15), @cyclingId),
       (nextval('event_pk_seq'), 'Tour de Suisse', cyd(6, 15), cyd(6, 22), @cyclingId),
       (nextval('event_pk_seq'), 'Giro Women', cyd(7, 06), cyd(7, 13), @cyclingId),
       (nextval('event_pk_seq'), 'Tour de France', cyd(7, 05), cyd(7, 27), @cyclingId),
       (nextval('event_pk_seq'), 'Tour de France Femmes', cyd(7, 26), cyd(8, 03), @cyclingId),
       (nextval('event_pk_seq'), 'Clásica de San Sebastián', cyd(8, 02), cyd(8, 02),
        @cyclingId),
       (nextval('event_pk_seq'), 'Renewi Tour', cyd(8, 20), cyd(8, 24), @cyclingId),
       (nextval('event_pk_seq'), 'Vuelta a España', cyd(8, 23), cyd(9, 14), @cyclingId),
       (nextval('event_pk_seq'), 'Tour of Britain', cyd(9, 02), cyd(9, 07), @cyclingId),
       (nextval('event_pk_seq'), 'GP Québec', cyd(9, 12), cyd(9, 12), @cyclingId),
       (nextval('event_pk_seq'), 'GP Montréal', cyd(9, 14), cyd(9, 14), @cyclingId),
       (nextval('event_pk_seq'), 'World Championships', cyd(9, 21), cyd(9, 28), @cyclingId),
       (nextval('event_pk_seq'), 'Tour of Lombardy', cyd(10, 11), cyd(10, 11), @cyclingId),
       (nextval('event_pk_seq'), 'Paris – Tours', cyd(10, 12), cyd(10, 12), @cyclingId),
       (nextval('event_pk_seq'), 'Tour Down Under', nyd(1, 21), nyd(1, 26), @cyclingId),
       (nextval('event_pk_seq'), 'Tour of Valencia', nyd(2, 05), nyd(2, 09), @cyclingId),
       (nextval('event_pk_seq'), 'UAE Tour', nyd(2, 17), nyd(2, 23), @cyclingId),
       (nextval('event_pk_seq'), 'Ruta del Sol', nyd(2, 19), nyd(2, 23), @cyclingId),
       (nextval('event_pk_seq'), 'Volta ao Algarve', nyd(2, 19), nyd(2, 23), @cyclingId),
       (nextval('event_pk_seq'), 'O Gran Camiño', nyd(2, 26), nyd(3, 03), @cyclingId),
       (nextval('event_pk_seq'), 'Omloop Het Nieuwsblad', nyd(3, 01), nyd(3, 01), @cyclingId),
       (nextval('event_pk_seq'), 'Kuurne – Brussels – Kuurne', nyd(3, 02), nyd(3, 02), @cyclingId),
       (nextval('event_pk_seq'), 'Strade Bianche Donne', nyd(3, 08), nyd(3, 08), @cyclingId),
       (nextval('event_pk_seq'), 'Strade Bianche', nyd(3, 08), nyd(3, 08), @cyclingId),
       (nextval('event_pk_seq'), 'Paris – Nice', nyd(3, 09), nyd(3, 16), @cyclingId),
       (nextval('event_pk_seq'), 'Tirreno – Adriatico', nyd(3, 10), nyd(3, 16), @cyclingId),
       (nextval('event_pk_seq'), 'Milan – San Remo (women)', nyd(3, 22), nyd(3, 22), @cyclingId),
       (nextval('event_pk_seq'), 'Milan – San Remo (men)', nyd(3, 22), nyd(3, 22), @cyclingId),
       (nextval('event_pk_seq'), 'Volta a Catalunya', nyd(3, 24), nyd(3, 30), @cyclingId),
       (nextval('event_pk_seq'), 'E3 Saxo Classic', nyd(3, 28), nyd(3, 28), @cyclingId),
       (nextval('event_pk_seq'), 'Dwars door Vlaanderen', nyd(4, 02), nyd(4, 02), @cyclingId),
       (nextval('event_pk_seq'), 'Tour of Flanders (women)', nyd(4, 06), nyd(4, 06), @cyclingId),
       (nextval('event_pk_seq'), 'Tour of Flanders (men)', nyd(4, 06), nyd(4, 06), @cyclingId),
       (nextval('event_pk_seq'), 'Itzulia Basque Country', nyd(4, 07), nyd(4, 12), @cyclingId),
       (nextval('event_pk_seq'), 'Paris – Roubaix Femmes', nyd(4, 12), nyd(4, 12), @cyclingId),
       (nextval('event_pk_seq'), 'Paris – Roubaix', nyd(4, 13), nyd(4, 13), @cyclingId),
       (nextval('event_pk_seq'), 'Brabantse Pijl', nyd(4, 18), nyd(4, 18), @cyclingId),
       (nextval('event_pk_seq'), 'Amstel Gold Race (women)', nyd(4, 20), nyd(4, 20), @cyclingId),
       (nextval('event_pk_seq'), 'Amstel Gold Race (men)', nyd(4, 20), nyd(4, 20), @cyclingId),
       (nextval('event_pk_seq'), 'Tour of the Alps', nyd(4, 21), nyd(4, 25), @cyclingId),
       (nextval('event_pk_seq'), 'Flèche Wallonne Femmes', nyd(4, 23), nyd(4, 23), @cyclingId),
       (nextval('event_pk_seq'), 'Flèche Wallonne', nyd(4, 23), nyd(4, 23), @cyclingId),
       (nextval('event_pk_seq'), 'Bastogne – Liège Femmes', nyd(4, 27), nyd(4, 27), @cyclingId),
       (nextval('event_pk_seq'), 'Liège – Bastogne – Liège', nyd(4, 27), nyd(4, 27), @cyclingId),
       (nextval('event_pk_seq'), 'Tour de Romandie', nyd(5, 29), nyd(6, 04), @cyclingId),
       (nextval('event_pk_seq'), 'Vuelta Femenina', nyd(5, 04), nyd(5, 10), @cyclingId),
       (nextval('event_pk_seq'), 'Giro d’Italia', nyd(5, 09), nyd(6, 01), @cyclingId),
       (nextval('event_pk_seq'), 'Critérium du Dauphiné', nyd(6, 08), nyd(6, 15), @cyclingId),
       (nextval('event_pk_seq'), 'Tour de Suisse', nyd(6, 15), nyd(6, 22), @cyclingId),
       (nextval('event_pk_seq'), 'Giro Women', nyd(7, 06), nyd(7, 13), @cyclingId),
       (nextval('event_pk_seq'), 'Tour de France', nyd(7, 05), nyd(7, 27), @cyclingId),
       (nextval('event_pk_seq'), 'Tour de France Femmes', nyd(7, 26), nyd(8, 03), @cyclingId),
       (nextval('event_pk_seq'), 'Clásica de San Sebastián', nyd(8, 02), nyd(8, 02), @cyclingId),
       (nextval('event_pk_seq'), 'Renewi Tour', nyd(8, 20), nyd(8, 24), @cyclingId),
       (nextval('event_pk_seq'), 'Vuelta a España', nyd(8, 23), nyd(9, 14), @cyclingId),
       (nextval('event_pk_seq'), 'Tour of Britain', nyd(9, 02), nyd(9, 07), @cyclingId),
       (nextval('event_pk_seq'), 'GP Québec', nyd(9, 12), nyd(9, 12), @cyclingId),
       (nextval('event_pk_seq'), 'GP Montréal', nyd(9, 14), nyd(9, 14), @cyclingId),
       (nextval('event_pk_seq'), 'World Championships', nyd(9, 21), nyd(9, 28), @cyclingId),
       (nextval('event_pk_seq'), 'Tour of Lombardy', nyd(10, 11), nyd(10, 11), @cyclingId),
       (nextval('event_pk_seq'), 'Paris – Tours', nyd(10, 12), nyd(10, 12), cyclingId)
;
END $$;
