INSERT INTO t_hobby (id, name)
VALUES (nextval('hobby_pk_seq'), 'Painting'),
       (nextval('hobby_pk_seq'), 'Drawing'),
       (nextval('hobby_pk_seq'), 'Digital Art'),
       (nextval('hobby_pk_seq'), 'Photography'),
       (nextval('hobby_pk_seq'), 'Writing'),
       (nextval('hobby_pk_seq'), 'Knitting'),
       (nextval('hobby_pk_seq'), 'Crocheting'),
       (nextval('hobby_pk_seq'), 'Woodworking'),
       (nextval('hobby_pk_seq'), 'Running'),
       (nextval('hobby_pk_seq'), 'Cycling'),
       (nextval('hobby_pk_seq'), 'Swimming'),
       (nextval('hobby_pk_seq'), 'Hiking'),
       (nextval('hobby_pk_seq'), 'Dancing'),
       (nextval('hobby_pk_seq'), 'Yoga'),
       (nextval('hobby_pk_seq'), 'Weightlifting'),
       (nextval('hobby_pk_seq'), 'Reading'),
       (nextval('hobby_pk_seq'), 'Crosswords'),
       (nextval('hobby_pk_seq'), 'Sudoku'),
       (nextval('hobby_pk_seq'), 'Chess'),
       (nextval('hobby_pk_seq'), 'Learning Languages'),
       (nextval('hobby_pk_seq'), 'Coding'),
       (nextval('hobby_pk_seq'), 'Cooking'),
       (nextval('hobby_pk_seq'), 'Baking'),
       (nextval('hobby_pk_seq'), 'Gardening'),
       (nextval('hobby_pk_seq'), 'Volunteering'),
       (nextval('hobby_pk_seq'), 'Board Games'),
       (nextval('hobby_pk_seq'), 'Book Clubs');