CREATE
OR REPLACE FUNCTION nyd(month INT, day INT) 
RETURNS DATE AS $$
    SELECT make_date(EXTRACT(YEAR FROM CURRENT_DATE)::INT + 1, month, day);
$$ LANGUAGE sql IMMUTABLE;

CREATE
OR REPLACE FUNCTION cyd(month INT, day INT) 
RETURNS DATE AS $$
    SELECT make_date(EXTRACT(YEAR FROM CURRENT_DATE)::INT, month, day);
$$ LANGUAGE sql IMMUTABLE;