DO
$$
    DECLARE
        chessId   INT;
        cyclingId INT;
        runningId INT;
        sudokuId INT;
    BEGIN
        SELECT id
        INTO chessId
        FROM t_hobby
        WHERE name = 'Chess';

        SELECT id
        INTO cyclingId
        FROM t_hobby
        WHERE name = 'Cycling';

        SELECT id
        INTO runningId
        FROM t_hobby
        WHERE name = 'Running';

        SELECT id
        INTO sudokuId
        FROM t_hobby
        WHERE name = 'Sudoku';

        INSERT INTO t_event(id, title, start_date, end_date, hobby_fk, skill_level)
        VALUES (nextval('event_pk_seq'), 'Tata Steel Masters', cyd(1, 17), cyd(2, 2), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Shenzhen Masters', cyd(3, 23), cyd(4, 1), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'American Cup', cyd(3, 15), cyd(3, 24), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Superbet Chess Classic Romania', cyd(5, 7), cyd(5, 16), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Norway Chess', cyd(5, 26), cyd(6, 6), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'UzChess Cup', cyd(6, 19), cyd(6, 27), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Chennai Grand Masters', cyd(8, 7), cyd(8, 16), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Sinquefield Cup', cyd(7, 18), cyd(8, 28), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Grand Swiss', cyd(9, 3), cyd(9, 15), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'U.S. Chess Championship', cyd(10, 11), cyd(10, 25), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Chess World Cup', cyd(10, 31), cyd(11, 27), @chessId, 'EXPERT');
        INSERT INTO t_event(id, title, start_date, end_date, hobby_fk, skill_level)
        VALUES (nextval('event_pk_seq'), 'Tata Steel Masters', nyd(1, 17), nyd(2, 2), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Shenzhen Masters', nyd(3, 23), nyd(4, 1), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'American Cup', nyd(3, 15), nyd(3, 24), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Superbet Chess Classic Romania', nyd(5, 7), nyd(5, 16), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Norway Chess', nyd(5, 26), nyd(6, 6), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'UzChess Cup', nyd(6, 19), nyd(6, 27), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Chennai Grand Masters', nyd(8, 7), nyd(8, 16), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Sinquefield Cup', nyd(7, 18), nyd(8, 28), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Grand Swiss', nyd(9, 3), nyd(9, 15), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'U.S. Chess Championship', nyd(10, 11), nyd(10, 25), @chessId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Chess World Cup', nyd(10, 31), nyd(11, 27), @chessId, 'EXPERT');

        INSERT INTO t_event(id, title, start_date, end_date, hobby_fk, skill_level)
        VALUES (nextval('event_pk_seq'), 'Tour Down Under', cyd(1, 21), cyd(1, 26), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour of Valencia', cyd(2, 5), cyd(2, 9), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'UAE Tour', cyd(2, 17), cyd(2, 23), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Ruta del Sol', cyd(2, 19), cyd(2, 23), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Volta ao Algarve', cyd(2, 19), cyd(2, 23), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'O Gran Camiño', cyd(2, 26), cyd(3, 3), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Omloop Het Nieuwsblad', cyd(3, 1), cyd(3, 1), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Kuurne – Brussels – Kuurne', cyd(3, 2), cyd(3, 2),
                @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Strade Bianche Donne', cyd(3, 8), cyd(3, 8), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Strade Bianche', cyd(3, 8), cyd(3, 8), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Paris – Nice', cyd(3, 9), cyd(3, 16), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tirreno – Adriatico', cyd(3, 10), cyd(3, 16), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Milan – San Remo (women)', cyd(3, 22), cyd(3, 22),
                @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Milan – San Remo (men)', cyd(3, 22), cyd(3, 22), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Volta a Catalunya', cyd(3, 24), cyd(3, 30), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'E3 Saxo Classic', cyd(3, 28), cyd(3, 28), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Dwars door Vlaanderen', cyd(4, 2), cyd(4, 2), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour of Flanders (women)', cyd(4, 6), cyd(4, 6),
                @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour of Flanders (men)', cyd(4, 6), cyd(4, 6), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Itzulia Basque Country', cyd(4, 7), cyd(4, 12), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Paris – Roubaix Femmes', cyd(4, 12), cyd(4, 12), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Paris – Roubaix', cyd(4, 13), cyd(4, 13), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Brabantse Pijl', cyd(4, 18), cyd(4, 18), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Amstel Gold Race (women)', cyd(4, 20), cyd(4, 20),
                @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Amstel Gold Race (men)', cyd(4, 20), cyd(4, 20), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour of the Alps', cyd(4, 21), cyd(4, 25), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Flèche Wallonne Femmes', cyd(4, 23), cyd(4, 23), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Flèche Wallonne', cyd(4, 23), cyd(4, 23), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Bastogne – Liège Femmes', cyd(4, 27), cyd(4, 27), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Liège – Bastogne – Liège', cyd(4, 27), cyd(4, 27),
                @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Eschborn Frankfurt Skyline', cyd(5, 1), cyd(5, 1), @cyclingId, 'BEGINNER'),
               (nextval('event_pk_seq'), 'Eschborn Frankfurt Express', cyd(5, 1), cyd(5, 1), @cyclingId,
                'INTERMEDIATE'),
               (nextval('event_pk_seq'), 'Eschborn Frankfurt Classic', cyd(5, 1), cyd(5, 1), @cyclingId, 'ADVANCED'),
               (nextval('event_pk_seq'), 'Tour de Romandie', cyd(5, 29), cyd(6, 4), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Vuelta Femenina', cyd(5, 4), cyd(5, 10), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Giro d’Italia', cyd(5, 9), cyd(6, 1), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Critérium du Dauphiné', cyd(6, 8), cyd(6, 15), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour de Suisse', cyd(6, 15), cyd(6, 22), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Rad am Ring 24h 1er', cyd(6, 24), cyd(6, 26), @cyclingId, 'ADVANCED'),
               (nextval('event_pk_seq'), 'Rad am Ring 24h 2er', cyd(6, 24), cyd(6, 26), @cyclingId, 'ADVANCED'),
               (nextval('event_pk_seq'), 'Rad am Ring 24h 4er', cyd(6, 24), cyd(6, 26), @cyclingId, 'ADVANCED'),
               (nextval('event_pk_seq'), 'Rad am Ring 24h 8er', cyd(6, 24), cyd(6, 26), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Rad am Ring 75km', cyd(6, 25), cyd(6, 25), @cyclingId, 'INTERMEDIATE'),
               (nextval('event_pk_seq'), 'Rad am Ring 150km', cyd(6, 25), cyd(6, 25), @cyclingId, 'ADVANCED'),
               (nextval('event_pk_seq'), 'Rad am Ring Tourenfahrt', cyd(6, 26), cyd(6, 26), @cyclingId, 'BEGINNER'),
               (nextval('event_pk_seq'), 'Giro Women', cyd(7, 6), cyd(7, 13), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour de France', cyd(7, 5), cyd(7, 27), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour de France Femmes', cyd(7, 26), cyd(8, 3), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Clásica de San Sebastián', cyd(8, 2), cyd(8, 2),
                @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Renewi Tour', cyd(8, 20), cyd(8, 24), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Vuelta a España', cyd(8, 23), cyd(9, 14), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour of Britain', cyd(9, 2), cyd(9, 7), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'GP Québec', cyd(9, 12), cyd(9, 12), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'GP Montréal', cyd(9, 14), cyd(9, 14), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'World Championships', cyd(9, 21), cyd(9, 28), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour of Lombardy', cyd(10, 11), cyd(10, 11), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Paris – Tours', cyd(10, 12), cyd(10, 12), @cyclingId, 'EXPERT');
        INSERT INTO t_event(id, title, start_date, end_date, hobby_fk, skill_level)
        VALUES (nextval('event_pk_seq'), 'Tour Down Under', nyd(1, 21), nyd(1, 26), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour of Valencia', nyd(2, 5), nyd(2, 9), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'UAE Tour', nyd(2, 17), nyd(2, 23), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Ruta del Sol', nyd(2, 19), nyd(2, 23), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Volta ao Algarve', nyd(2, 19), nyd(2, 23), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'O Gran Camiño', nyd(2, 26), nyd(3, 3), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Omloop Het Nieuwsblad', nyd(3, 1), nyd(3, 1), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Kuurne – Brussels – Kuurne', nyd(3, 2), nyd(3, 2), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Strade Bianche Donne', nyd(3, 8), nyd(3, 8), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Strade Bianche', nyd(3, 8), nyd(3, 8), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Paris – Nice', nyd(3, 9), nyd(3, 16), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tirreno – Adriatico', nyd(3, 10), nyd(3, 16), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Milan – San Remo (women)', nyd(3, 22), nyd(3, 22), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Milan – San Remo (men)', nyd(3, 22), nyd(3, 22), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Volta a Catalunya', nyd(3, 24), nyd(3, 30), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'E3 Saxo Classic', nyd(3, 28), nyd(3, 28), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Dwars door Vlaanderen', nyd(4, 2), nyd(4, 2), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour of Flanders (women)', nyd(4, 6), nyd(4, 6), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour of Flanders (men)', nyd(4, 6), nyd(4, 6), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Itzulia Basque Country', nyd(4, 7), nyd(4, 12), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Paris – Roubaix Femmes', nyd(4, 12), nyd(4, 12), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Paris – Roubaix', nyd(4, 13), nyd(4, 13), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Brabantse Pijl', nyd(4, 18), nyd(4, 18), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Amstel Gold Race (women)', nyd(4, 20), nyd(4, 20), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Amstel Gold Race (men)', nyd(4, 20), nyd(4, 20), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour of the Alps', nyd(4, 21), nyd(4, 25), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Flèche Wallonne Femmes', nyd(4, 23), nyd(4, 23), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Flèche Wallonne', nyd(4, 23), nyd(4, 23), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Bastogne – Liège Femmes', nyd(4, 27), nyd(4, 27), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Liège – Bastogne – Liège', nyd(4, 27), nyd(4, 27), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Eschborn Frankfurt Skyline', nyd(5, 1), nyd(5, 1), @cyclingId, 'BEGINNER'),
               (nextval('event_pk_seq'), 'Eschborn Frankfurt Express', nyd(5, 1), nyd(5, 1), @cyclingId,
                'INTERMEDIATE'),
               (nextval('event_pk_seq'), 'Eschborn Frankfurt Classic', nyd(5, 1), nyd(5, 1), @cyclingId, 'ADVANCED'),
               (nextval('event_pk_seq'), 'Tour de Romandie', nyd(5, 29), nyd(6, 4), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Vuelta Femenina', nyd(5, 4), nyd(5, 10), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Giro d’Italia', nyd(5, 9), nyd(6, 1), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Critérium du Dauphiné', nyd(6, 8), nyd(6, 15), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour de Suisse', nyd(6, 15), nyd(6, 22), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Rad am Ring 24h 1er', nyd(6, 24), nyd(6, 26), @cyclingId, 'ADVANCED'),
               (nextval('event_pk_seq'), 'Rad am Ring 24h 2er', nyd(6, 24), nyd(6, 26), @cyclingId, 'ADVANCED'),
               (nextval('event_pk_seq'), 'Rad am Ring 24h 4er', nyd(6, 24), nyd(6, 26), @cyclingId, 'ADVANCED'),
               (nextval('event_pk_seq'), 'Rad am Ring 24h 8er', nyd(6, 24), nyd(6, 26), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Rad am Ring 75km', nyd(6, 25), nyd(6, 25), @cyclingId, 'INTERMEDIATE'),
               (nextval('event_pk_seq'), 'Rad am Ring 150km', nyd(6, 25), nyd(6, 25), @cyclingId, 'ADVANCED'),
               (nextval('event_pk_seq'), 'Rad am Ring Tourenfahrt', nyd(6, 26), nyd(6, 26), @cyclingId, 'BEGINNER'),
               (nextval('event_pk_seq'), 'Giro Women', nyd(7, 6), nyd(7, 13), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour de France', nyd(7, 5), nyd(7, 27), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour de France Femmes', nyd(7, 26), nyd(8, 3), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Clásica de San Sebastián', nyd(8, 2), nyd(8, 2), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Renewi Tour', nyd(8, 20), nyd(8, 24), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Vuelta a España', nyd(8, 23), nyd(9, 14), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour of Britain', nyd(9, 2), nyd(9, 7), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'GP Québec', nyd(9, 12), nyd(9, 12), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'GP Montréal', nyd(9, 14), nyd(9, 14), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'World Championships', nyd(9, 21), nyd(9, 28), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Tour of Lombardy', nyd(10, 11), nyd(10, 11), @cyclingId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Paris – Tours', nyd(10, 12), nyd(10, 12), cyclingId, 'EXPERT');
        INSERT INTO t_event(id, title, start_date, end_date, hobby_fk, skill_level)
        VALUES (nextval('event_pk_seq'), 'World Marathon Challenge – Antarctica', cyd(1, 31), cyd(1, 31), @runningId,
                'EXPERT'),
               (nextval('event_pk_seq'), 'Tokyo Marathon', cyd(3, 1), cyd(3, 1), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Rome Marathon', cyd(3, 22), cyd(3, 22), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Cluj-Napoca Marathon', cyd(3, 28), cyd(3, 28), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Milwaukee Marathon', cyd(4, 11), cyd(4, 11), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Paris Marathon', cyd(4, 12), cyd(4, 12), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Milano Marathon', cyd(4, 12), cyd(4, 12), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Limone Lake Garda Marathon', cyd(4, 12), cyd(4, 12), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Santa Eulària Ibiza Marathon', cyd(4, 18), cyd(4, 18), @runningId,
                'EXPERT'),
               (nextval('event_pk_seq'), 'Vienna City Marathon', cyd(4, 19), cyd(4, 19), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Boston Marathon', cyd(4, 20), cyd(4, 20), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'London Marathon', cyd(4, 26), cyd(4, 26), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'B2C Run Aachen', cyd(4, 28), cyd(4, 28), @runningId, 'BEGINNER'),
               (nextval('event_pk_seq'), 'B2C Run Karlsruhe', cyd(5, 7), cyd(5, 7), @runningId, 'BEGINNER'),
               (nextval('event_pk_seq'), 'Merck Firmenlauf 3km', cyd(5, 12), cyd(5, 12), @runningId, 'BEGINNER'),
               (nextval('event_pk_seq'), 'Merck Firmenlauf 5km', cyd(5, 12), cyd(5, 12), @runningId, 'INTERMEDIATE'),
               (nextval('event_pk_seq'), 'Merck Firmenlauf 10km', cyd(5, 12), cyd(5, 12), @runningId, 'ADVANCED'),
               (nextval('event_pk_seq'), 'Cape Town Marathon', cyd(5, 24), cyd(5, 24), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Taupō Marathon', cyd(8, 1), cyd(8, 1), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Sydney Marathon', cyd(8, 30), cyd(8, 30), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'B2C Run Köln', cyd(9, 9), cyd(9, 9), @runningId, 'BEGINNER'),
               (nextval('event_pk_seq'), 'Berlin Marathon', cyd(9, 27), cyd(9, 27), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Chicago Marathon', cyd(10, 11), cyd(10, 11), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'New York City Marathon', cyd(11, 1), cyd(11, 1), @runningId, 'EXPERT');
        INSERT INTO t_event(id, title, start_date, end_date, hobby_fk, skill_level)
        VALUES (nextval('event_pk_seq'), 'World Marathon Challenge – Antarctica', nyd(1, 31), nyd(1, 31), @runningId,
                'EXPERT'),
               (nextval('event_pk_seq'), 'Tokyo Marathon', nyd(3, 1), nyd(3, 1), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Rome Marathon', nyd(3, 22), nyd(3, 22), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Cluj-Napoca Marathon', nyd(3, 28), nyd(3, 28), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Milwaukee Marathon', nyd(4, 11), nyd(4, 11), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Paris Marathon', nyd(4, 12), nyd(4, 12), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Milano Marathon', nyd(4, 12), nyd(4, 12), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Limone Lake Garda Marathon', nyd(4, 12), nyd(4, 12), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Santa Eulària Ibiza Marathon', nyd(4, 18), nyd(4, 18), @runningId,
                'EXPERT'),
               (nextval('event_pk_seq'), 'Vienna City Marathon', nyd(4, 19), nyd(4, 19), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Boston Marathon', nyd(4, 20), nyd(4, 20), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'London Marathon', nyd(4, 26), nyd(4, 26), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'B2C Run Aachen', nyd(4, 28), nyd(4, 28), @runningId, 'BEGINNER'),
               (nextval('event_pk_seq'), 'B2C Run Karlsruhe', nyd(5, 7), nyd(5, 7), @runningId, 'BEGINNER'),
               (nextval('event_pk_seq'), 'Merck Firmenlauf 3km', nyd(5, 12), nyd(5, 12), @runningId, 'BEGINNER'),
               (nextval('event_pk_seq'), 'Merck Firmenlauf 5km', nyd(5, 12), nyd(5, 12), @runningId, 'INTERMEDIATE'),
               (nextval('event_pk_seq'), 'Merck Firmenlauf 10km', nyd(5, 12), nyd(5, 12), @runningId, 'ADVANCED'),
               (nextval('event_pk_seq'), 'Cape Town Marathon', nyd(5, 24), nyd(5, 24), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Taupō Marathon', nyd(8, 1), nyd(8, 1), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Sydney Marathon', nyd(8, 30), nyd(8, 30), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'B2C Run Köln', nyd(9, 9), nyd(9, 9), @runningId, 'BEGINNER'),
               (nextval('event_pk_seq'), 'Berlin Marathon', nyd(9, 27), nyd(9, 27), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'Chicago Marathon', nyd(10, 11), nyd(10, 11), @runningId, 'EXPERT'),
               (nextval('event_pk_seq'), 'New York City Marathon', nyd(11, 1), nyd(11, 1), @runningId, 'EXPERT');

        INSERT INTO t_event(id, title, start_date, end_date, hobby_fk, skill_level)
        VALUES (nextval('event_pk_seq'), 'Sudoku Basecamp', cyd(12, 1), cyd(12, 1), @sudokuId, 'BEGINNER'),
               (nextval('event_pk_seq'), 'Sudoku Booster', cyd(12, 2), cyd(12, 2), @sudokuId, 'INTERMEDIATE'),
               (nextval('event_pk_seq'), 'Sudoku Basecamp', nyd(12, 1), nyd(12, 1), @sudokuId, 'BEGINNER'),
               (nextval('event_pk_seq'), 'Sudoku Booster', nyd(12, 2), nyd(12, 2), @sudokuId, 'INTERMEDIATE');
    END
$$;
